### ISSUE TITLE
Change next/back arrow buttons in guide to next/back buttons like the ones in onboarding

### ISSUE THREAD

**Issue by juliadeng123** [Michelle2317/GoldiBite#84]

**Comment by klee616** [comment]
please checkout 84-change-nextback-arrow-buttons-in-guide-to-nextback-buttons-like-the-ones-in-onboarding, and test it.
Because we use the ScrollView in the guides, so I difficult to align the button in the same location.  
![IMG_2796](https://github.com/user-attachments/assets/05b87e4a-dbdf-4533-b995-a31b66b56869)
